### ISSUE TITLE
Setup code for Lightbulb and Lock

### ISSUE THREAD

**Issue by mg0rski** [apple/HomeKitADK#10]
Hello, could you please explain how the 8-digit key is generated and what's the key for pairing the Lightbulb and Lock Application examples?

I've been trying to pair the accessory for a while but with no effect. 
App quits due to:

`2019-12-28'T'23:08:00'Z'	Error	[com.apple.mfi.HomeKit.Platform:AccessorySetup] No setup code found in key-value store.`

Meanwhile I noticed that some files in .HomeKitStore are read, especially .HomeKitStore/40.10 which not exist, so I made a try in creation this file filled with 400 bytes (I get the value from the code). Now it does not quit, it's waiting for the 8-digit key but I don't have even an idea what it could be... 

Could you please help with that? I'm running Linux build. Thanks in advance.

**Comment by leonrinkel** [comment]
The code is 111-22-333.

**Comment by mg0rski** [comment]
Thank you @leonrinkel! This setup code works, only needs to put salt+veryfier data into file in .HomeKitStore/40.10.

**Comment by leonrinkel** [comment]
I’m not sure about Linux, but on Mac it does automatically create the `.HomeKitStore` using the mocked default values. I guess a clean start without any modifications to `.HomeKitStore` should also work.

**Comment by d4rkmen** [comment]
On Linux need to use the AccessorySetupGenerator tool to make a keyvalues dictionary then it run smooth

**Comment by leonrinkel** [comment]
Ah you're right. I found that something like `Tools/provision_raspi.sh --category 5 .HomeKitStore` is pretty convenient for provisioning even if you're not using a Raspberry Pi.

**Comment by hubertwang** [comment]
Anyone know where the generated .HomeKitStore provisioning file should be put on Mac?
I tried to run it on my Mac, but still stuck on pairing.

**Comment by leonrinkel** [comment]
The applications look for .HomeKitStore in your current directory (pwd). So if you execute the application from the repos root directory, .HomeKitStore is expected to be in the repos root.

**Comment by hubertwang** [comment]
> The applications look for .HomeKitStore in your current directory (pwd). So if you execute the application from the repos root directory, .HomeKitStore is expected to be in the repos root.

Thank you. Hmm, it's still not working.
I execute the application from root directory of repo, and it did create .HomeKitStore and 40.10, 40.11 file . My iPhone can find the accessory Acme Light Bulb, but pincode and QR code doesn't seem to work.

BTW, I noticed one thing, if I run the application without provisioning profiles, it will create a dictionary file named .HomeKitStore, which is not a directory.
I'll try if my raspberry pi can get it work.

--
macOS 10.15.2

**Comment by leonrinkel** [comment]
As you already noticed the format is different on Mac. The provisioning tool can’t be used. Pairing should still work using the default hardcoded setup code 111-22-333.

**Comment by hubertwang** [comment]
> As you already noticed the format is different on Mac. The provisioning tool can’t be used. Pairing should still work using the default hardcoded setup code 111-22-333.

Got it, thank you so much.
I still cannot get it to work though. Seems iOS app can find the accessory, but unable to pair.
During my pairing action, there is no message output from Lightbulb.OpenSSL.

2020-02-27'T'09:48:57'Z'	Info	Accessory Server State did update: Running.
2020-02-27 17:48:57.533 Lightbulb.OpenSSL[55762:394831] callback completedan

I'll try to build it on another mac.

**Comment by hubertwang** [comment]
It works on my own mac. Seems it's my environment issue.
Thank you all for your assistance!

**Comment by aivs** [comment]
Hi! I generated a data for setup code, where should I put it?
By the way, I tried adding with the standard code "111-22-333", and the adding failed due to timeout.

```
parallels@ubuntu-linux-22-04-desktop:~/HomeKitADK$ ./Output/Linux-aarch64-unknown-linux-gnu/Debug/Tools/AccessorySetupGenerator.OpenSSL --ip --category 5
1
641-42-238
DB20811F5D6D857AFB1D43A8261E5C3F
3EAB154CC433C5A41C9E8DDC050FBBC16A9421BB18CCB322E40B1871F95F0D084FD286FF162496233BE9A2F414FE9A10F487BB826BEF4B0DF4588B74CA4AC27EB7E4F5C4CCEC30AC05AAEF6B671005F91866E040A6452BF480A065820376F4DD66805ABABC21B7D6799D69123CE97CEBA436BBDF8DBF496D0B005EADBC27F8EAA62F4DF587C57C7D513136473541A8143B1A7626619E5C23A7E25E1F36960B8DB4AEBDFACAC2BF14E859D79CF2AF8B5D21F6438270D6DE9FB826A132125DCBD4A2C27CAE1D10D8E02EC476E2562C470323EBAC99EFC1649B98F73B84C96BB9B18111F3C85248A0AA91604BD19270BFB8F8C603C012236D32747E7E8AEBEC5362D12BD03878361E89BF34B312A7F1B5B69BA37C360BBBEE15C007A255D6161428C2A42D6FC446FB4985A9D53B8DDFCCDABEE88710BFAB1A77E9C503C92A5C44E1B49DECCC142B492F31E5F5C656F6FD46D8D1DE26A4AC0C83CB502725A7A3454D5240B199A6CD0BBDA753AE0918D084B702B8DDD354A77F1FD2C3A54CF235F570
YH7H
X-HM://00532SFJ2YH7H
```
