### ISSUE TITLE
Docker build necessary ?

### ISSUE THREAD

**Issue by Clovel** [apple/HomeKitADK#23]
Why exactly do we need to run make in a docker container. Of course I understand the benefits of doing so, but shouldn't it be an option when running make for the first time ? Something like `make DOCKER_BUILD=y` or so ?

**Comment by pgravel-com** [comment]
No, it is not strictly necessary and adding a flag should be fairly trivial.

**Comment by Clovel** [comment]
Ok @pgravel-com. I was thinking of that because of cases where some people can't use Docker (VT-x deactivated by IT dept., WSL, etc) but still want to compile and contribute.

**Comment by leonrinkel** [comment]
Building without Docker is already possible by running something like `make -f Build/Makefile` instead of using the default root-level Makefile. A flag would make that even clearer.

**Comment by Clovel** [comment]
> Building without Docker is already possible by running something like `make -f Build/Makefile` instead of using the default root-level Makefile. A flag would make that even clearer.

Exactly my point. I (or someone else) should look to implement this.

**Comment by rojer** [comment]
i don't really understand the rpoblem...
i'm using something like `make apps && Output/Linux-x86_64-pc-linux-gnu/Debug/IP/Applications/Lightbulb.OpenSSL` and it just works for me on ubuntu.
with all the dependencies installed, of course.

**Comment by aajain-com** [comment]
Like @rojer said, if `make` is being run inside a plain posix environment then you don't need docker at all. Reference: https://github.com/apple/HomeKitADK/blob/master/Makefile#L39-L4. The code `ifneq (,$(wildcard /.dockerenv))` already makes sure of that.

**Comment by Clovel** [comment]
> Like @rojer said, if `make` is being run inside a plain posix environment then you don't need docker at all. Reference: https://github.com/apple/HomeKitADK/blob/master/Makefile#L39-L4. The code `ifneq (,$(wildcard /.dockerenv))` already makes sure of that.

I do not have that experience. On a Linux system that doesn't have docker, I get : 
```
$ make apps
/bin/sh: 1: docker: not found
/bin/sh: 1: docker: not found
Makefile:58: recipe for target 'all' failed
make: *** [all] Error 127
```

I get the same result using `make TARGET=Linux apps`.
