### ISSUE TITLE
Doxygen documentation ?

### ISSUE THREAD

**Issue by Clovel** [apple/HomeKitADK#38]
Do we want/need a Doxygen documentation generation for this project ? Wouldn't it be a good idea to have one ? There are already lots of documentation comments in the code that could be used by Doxygen.

**Comment by Clovel** [comment]
This adds Doxygen & Dot to the dependencies and adding `sudo apt install doxygen graphviz` in the Dockerfile.

**Comment by Clovel** [comment]
I generated the Doxygen, and it already looks good.

**Comment by aajain-com** [comment]
@Clovel I have been meaning to do that too specifically for PAL APIs but haven't had time. Thanks for looking into it. Have you evaluated other document generators like Sphinx?

**Comment by Clovel** [comment]
> @Clovel I have been meaning to do that too specifically for PAL APIs but haven't had time. Thanks for looking into it. Have you evaluated other document generators like Sphinx?

You're welcome. I'm am not familiar with the other generators, as Doxygen is basically he standard for C/C++ where I work. 

Plus withgraphviz you can get great dependency graphs. I don't know if the other do that too.

**Comment by Clovel** [comment]
Just by looking at [this comparision](https://www.slant.co/versus/12123/22040/~doxygen_vs_sphinx), I have the feeling that Oxygen is better. It doesn't need another `Makefile`.
