### ISSUE TITLE
What is the purpose of the Docker images?

### ISSUE THREAD

**Issue by ehogeweg** [apple/HomeKitADK#42]
Hi,

I am trying to wrap my mind around the purpose of the Docker image(s). The nginx image builds and runs just fine, but it doesn't have any network adapters configured, so how are the examples supposed to run? <new to docker and wildly confused>

And re. the raspi image: When I run `docker build -f Dockerfile.Raspi -t raspi_image .` in an attempt to create a pi image I get the error below. Not sure if that is expected. 

```
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM dev-test/raspiadk-base as build
pull access denied for dev-test/raspiadk-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```

I am probably still missing something but I can't find anything in the available doc to help me out.

Please advice.

Kind Regards,

Erwin

**Comment by hao-gao** [comment]
1. ./Tools/raspi_sdcard_setup.sh helps you deploy a develop environment in your raspberry pi SD card, then 'docker import' the rootfs of the sd card, and you will get the 'dev-test/raspiadk-base' docker image. 
2. 'make TARGET=Raspi apps',  docker-run the image as a container, builds demo applications for you in the docker container
3. ./Tools/install.sh scp the demo executables to your pi and run it on pi.

**Comment by aajain-com** [comment]
The purpose of docker image for raspi is simply to aid in development of ADK for raspi platform on your host machine without having to ssh in to raspi and keep copying the code over to compile and run unit tests.

**Comment by ehogeweg** [comment]
I got it now. Thanks for the help all.
