### ISSUE TITLE
Build error caused by XCode SDK

### ISSUE THREAD

**Issue by Baptiste-Gouesbet** [apple/HomeKitADK#50]
Hello everyone,

I am having a compile error between openssl and Xcode SDK :
> In file included from /usr/local/Cellar/openssl@1.1/1.1.1g/include/openssl/crypto.h:415:
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/pthread.h:332:5: error: 
>       declaration of built-in function 'pthread_create' requires inclusion of the
>       header <pthread.h> [-Werror,-Wbuiltin-requires-header]
> int pthread_create(pthread_t _Nullable * _Nonnull __restrict,
>     ^
> 1 error generated.

I am compiling on a macOS Catalina.
Could you please help me with this problem ?

Thanks in advance

**Comment by conkerkh** [comment]
Use GCC instead of clang for compiler, its an issue with gcc

**Comment by Baptiste-Gouesbet** [comment]
Thank you very much :-)
