### ISSUE TITLE
Support for nRF52

### ISSUE THREAD

**Issue by GoRo33** [apple/HomeKitADK#52]
Hi! 

I saw that on one of the last updates there is new TARGET on documentation nRF52. I have question that anybody know that support for this microcontrollers has actually be added or this is some kind of mistake? 

I have tried to compile it with this target but without success.

`Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM ubuntu:18.04
 ---> 4e5021d210f6
Step 2/3 : RUN echo ========== Install dependencies ==========   && apt-get update && apt-get install -y     clang     gdb     git     libavahi-compat-libdnssd-dev     libssl-dev     make     openssh-server     perl     unzip     wget   && apt-get clean   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 7f623943446c
Step 3/3 : WORKDIR /build
 ---> Using cache
 ---> 5f555e6c81e6
Successfully built 5f555e6c81e6
make: *** No rule to make target 'Output/nRF52-/Test/Tests/HAPBLEEventTest.', needed by 'tests'.  Stop.
make: *** [all] Error 2`

**Comment by aajain-com** [comment]
nRF52 is currently not supported. We should remove it from the documentation to avoid any confusion.
