### ISSUE TITLE
API Documentation link on the README is broken

### ISSUE THREAD

**Issue by Pranay154** [apple/HomeKitADK#59]
**The following** `API Documentation` **link is broken (leads to a 404 error)** 

<img width="863" alt="Screenshot 2020-06-23 at 09 52 11" src="https://user-images.githubusercontent.com/37961978/85382888-4f827580-b537-11ea-9e53-a76670d48d28.png">

**The same applies for the following** `guidelines for contributing code`

<img width="1224" alt="Screenshot 2020-06-23 at 09 54 33" src="https://user-images.githubusercontent.com/37961978/85383206-9d977900-b537-11ea-8263-b27177e32b9b.png">

**Comment by aajain-com** [comment]
The link was meant to point to the location where the `make docs` will generate the documentation at. Will fix the documentation shortly.
