### ISSUE TITLE
Missing TV Characteristics / Services?

### ISSUE THREAD

**Issue by ikkysleepy** [apple/HomeKitADK#69]
Is the characteristics / services for TV missing or am I missing something? I see most of the other characteristics and services but nothing to deal with the remote and or the TV services. Is this in the works or out of scope of this project? Thanks.

**Comment by aajain-com** [comment]
@ikkysleepy in order to use the TV service you would need to use commercial version of the HomeKit ADK available through the MFi Program.

**Comment by maximkulkin** [comment]
@ikkysleepy if you plan to develop commercial accessories then you definitely need to get MFi certification and get access to commercial specification. But if you just want to do some hobby project, you can look for information on TV services and accessories in open-source HAP implementations, e.g. [this](https://github.com/maximkulkin/esp-ir-tv/blob/master/main/main.c) or [this](https://github.com/ikalchev/HAP-python/blob/dev/accessories/TV.py).

**Comment by ikkysleepy** [comment]
Thanks for the info @aajain-com . I have code already for a restful web API that turns on and off your tv via HDMI CEC and you can send commands locally to various technologies like android tv / wake on lan / restful web api / sockets for global cache / broad links / etc. on a raspberry pi. I even have a homebridge plugin , but I wanted to see how much effort and cost it will take to take it to the next level. It seems like I can't certify a raspberry pi as MFI device because of the lack of hardware encryption, is that correct?  If so then the MFI program will not result in anything. 

@maximkulkin  those projects look interesting, I wonder if I can use the code on raspberry pi hardware because I need the HDMI Port functionality and there is no ESP with HDMi output, AFIAK.  

Thanks for your responses.

**Comment by maximkulkin** [comment]
@ikkysleepy I have a python script that does similar things on Raspberry Pi:
* implement HomeKit TV accessory via HAP-python
* talks HDMI-CEC to detect TV state
* uses IR module to send various IR commands to TV (power on/off, volume control.. my dumb TV does not have rich HDMI-CEC support)
* uses IR module to talk to HDMI switch to switch between different inputs.

Email me if you want details on how to do that.

**Comment by Clovel** [comment]
A good idea would be to implement a layer that works whether or not you have HDMI-CEC rich support. 
Anybody would then plug that layer into their different APIs, either HDMI-CEC, IR, or a web API (like the Samsung TVs)

**Comment by ikkysleepy** [comment]
@maximkulkin  thanks for the support but I want the HDMI-CEC support. So the main reason why I made this project I am working on was for ease of use for my non-tech friends. The plan is to give them a raspberry pi with an image already installed and have them follow these steps: (1) plug in the cables (2) add the accessory on your iphone/ipad/macbook and (3) Say Siri, Turn ON/OFF TV.  I have this image and it works well, but it uses homebridge.

@Clovel The layer I have doesn't need HDMI-CEC to work, but the TV Accessory works best if it has a status and with HDMI CEC you can get a physical / real status if the TV Is on.  I have an IR Blaster and a little kid as well and the best solution for the past couple of years has still been HDMI-CEC.  Over the past 6 months the command to turn on/off my tv has just worked, which is great. I was looking at this project to see if I could drop homebridge and go with the Apple's Open HomeKit ADK but looks like you are limited in what you can do with it. 

BTW where is the more info about the image and how it homebridge plugin, if anyone is interested in it.
https://blog.tinyelectrons.com/homebridge
