### ISSUE TITLE
ADK/Tools/provisionraspi.sh

### ISSUE THREAD

**Issue by hubTab** [apple/HomeKitADK#83]
Related to the HomeKit ADK available on Github, 
even though the "HomeKit ADK Integration Guide - for ADK 5.1.pdf" references the ADK/Tools/provisionraspi.sh, the script does not exist.

Does anyone know why the ADK/Tools/provisionraspi.sh is not available in Apple MFI HomeKit ADK 5.1. zip, but it is available in the Github HK ADK? It looks like the Github script does not have the same format as documented in the "HomeKit ADK Integration Guide - for ADK 5.1.pdf".

**Comment by aajain-com** [comment]
@hubTab in ADK on Mfi the script is called as `provision_raspi.sh`. If you have specific questions about ADK versions on Mfi portal, please use Feedback assistant or your Mfi contacts to reach out to us instead of here.
